# Generated by Django 5.0.6 on 2024-06-07 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('RECURRING', 'Recurring'), ('SPECIFIC', 'Specific')], max_length=20)),
                ('price_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('date', models.DateField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='suppliers.supplier')),
            ],
        ),
    ]
