version: '3.9'
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: bookstoredb
      POSTGRES_USER: bookstoreuser
      POSTGRES_PASSWORD: bookstorepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bookstore:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: bookstoredb
      DB_USER: bookstoreuser
      DB_PASSWORD: bookstorepassword
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data:
