# Generated by Django 5.0.6 on 2024-06-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
