# Generated by Django 5.0.6 on 2024-06-08 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashoutflow',
            name='material',
        ),
        migrations.AddField(
            model_name='cashoutflow',
            name='content_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashoutflow',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outflows', to='suppliers.supplier'),
        ),
    ]
