# Generated by Django 5.0.6 on 2024-06-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_number',
            field=models.CharField(blank=True, editable=False, max_length=15, unique=True),
        ),
    ]
