# Generated by Django 5.0.6 on 2024-06-08 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_publication_price_total_publication_price_unit_and_more'),
        ('sales', '0003_sale_sale_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='book',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='publication.publication'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
