# Generated by Django 5.0.6 on 2024-06-14 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyers", "0001_initial"),
        ("sales", "0005_alter_sale_book_alter_sale_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="buyer",
            field=models.ForeignKey(
                default= 1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="buyers",
                to="buyers.buyer",
            ),
            preserve_default=False,
        ),
    ]
