# Generated by Django 5.0.6 on 2024-06-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_sale_buyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESSFUL", "Successful"),
                    ("PENDING", "Pending"),
                    ("CANCELED", "Canceled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
