# Generated by Django 5.0.6 on 2024-07-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_sale_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="sale_date",
            field=models.DateTimeField(),
        ),
    ]
