# Generated by Django 5.0.6 on 2024-06-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_publication_assembly_publication_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='price_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
