# Generated by Django 5.0.6 on 2024-06-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_publication_price_total_publication_price_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
