# Generated by Django 5.0.6 on 2024-06-01 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assembly', '0002_remove_bookassembly_page_count'),
        ('authors', '0002_authors_biography_authors_birthday_authors_name'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('page_count', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=50)),
                ('assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assembly', to='assembly.bookassembly')),
                ('author', models.ManyToManyField(related_name='author', to='authors.authors')),
                ('genres', models.ManyToManyField(related_name='genre', to='genres.genre')),
            ],
        ),
    ]
