# Generated by Django 5.0.6 on 2024-06-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_type', models.CharField(choices=[('perfect', 'Perfect Binding'), ('saddle', 'Saddle Stitch'), ('case', 'Case Binding'), ('spiral', 'Spiral Binding')], max_length=50)),
                ('paper_type', models.CharField(choices=[('glossy', 'Glossy'), ('matte', 'Matte'), ('recycled', 'Recycled'), ('bond', 'Bond')], max_length=50)),
                ('cover_type', models.CharField(choices=[('hardcover', 'Hardcover'), ('paperback', 'Paperback'), ('spiral', 'Spiral')], max_length=50)),
                ('page_count', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
