# Generated by Django 5.0.6 on 2024-06-08 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_remove_cashoutflow_material_cashoutflow_content_type_and_more'),
        ('sales', '0003_sale_sale_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashinflow',
            name='source',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='inflow', to='sales.sale'),
        ),
    ]
