# Generated by Django 5.0.6 on 2024-06-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0004_alter_cashinflow_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashinflow',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
