# Generated by Django 5.0.6 on 2024-06-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cashflow", "0005_alter_cashinflow_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashinflow",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="cashoutflow",
            options={"ordering": ["-date"]},
        ),
    ]
