# Generated by Django 5.0.6 on 2024-06-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookassembly',
            name='page_count',
        ),
    ]
